[package]
name = "qasm"
version = "0.1.0"
authors = ["Adam Kelly <adamkelly2201@gmail.com>"]
description = "A OPENQASM 2.0 Parser"

[dependencies]
regex = "0.2"

[dev-dependencies]
glob = "0.2"

[[bin]]
name = "main"
path = "examples/main.rs"
